# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice_text',
            new_name='choice',
        ),
    ]
