# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170220_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.IntegerField(default=2),
        ),
    ]
